"use client";

import { useMemo, useState } from "react";
import {
  ArrowDownRight,
  ArrowUpRight,
  ChevronRight,
  Download,
  ExternalLink,
  Filter,
  MoreHorizontal,
  Plus,
  Search,
  SlidersHorizontal,
  X,
} from "lucide-react";
import { DashboardFooter } from "@/components/dashboard-footer";
import { DashboardNav, DashboardTopBar } from "@/components/dashboard-nav";
import { INITIAL_PORTFOLIO, MOCK_NEWS, MOCK_STOCKS } from "@/lib/mock-data";
import type { NewsItem, StockItem, TabType } from "@/lib/types";

function Sparkline({ values, dark = false }: { values: number[]; dark?: boolean }) {
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = max - min || 1;
  const points = values.map((value, index) => `${(index / (values.length - 1)) * 100},${30 - ((value - min) / range) * 25}`).join(" ");
  return <svg viewBox="0 0 100 32" className="h-8 w-24" preserveAspectRatio="none" aria-hidden="true"><polyline points={points} fill="none" stroke={dark ? "#fff" : "#111"} strokeWidth="1.5" vectorEffect="non-scaling-stroke" /></svg>;
}

function Change({ value }: { value: number }) {
  const positive = value >= 0;
  return <span className="inline-flex items-center gap-1 font-mono text-xs font-bold text-black">{positive ? <ArrowUpRight className="h-3 w-3" /> : <ArrowDownRight className="h-3 w-3" />}{positive ? "+" : ""}{value.toFixed(2)}%</span>;
}

function SectionHeading({ eyebrow, title, action }: { eyebrow: string; title: string; action?: string }) {
  return <div className="mb-7 flex items-end justify-between gap-4"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[0.24em] text-neutral-500">{eyebrow}</p><h2 className="text-2xl font-semibold tracking-tight text-black">{title}</h2></div>{action && <button className="hidden items-center gap-2 text-xs font-bold uppercase tracking-wider text-neutral-500 hover:text-black sm:flex">{action}<ChevronRight className="h-3 w-3" /></button>}</div>;
}

function Metric({ label, value, note, large = false }: { label: string; value: string; note: string; large?: boolean }) {
  return <div className="border-t border-black pt-4"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-neutral-500">{label}</p><p className={`mt-3 font-mono font-medium tracking-tight text-black ${large ? "text-4xl" : "text-2xl"}`}>{value}</p><p className="mt-2 text-xs text-neutral-500">{note}</p></div>;
}

function StockRow({ stock, onSelect }: { stock: StockItem; onSelect: (stock: StockItem) => void }) {
  return <button onClick={() => onSelect(stock)} className="grid w-full grid-cols-[1.1fr_1fr_0.8fr_1fr_28px] items-center gap-4 border-b border-neutral-200 py-4 text-left transition-colors hover:bg-neutral-100"><div><p className="font-mono text-sm font-bold text-black">{stock.symbol}</p><p className="mt-1 truncate text-xs text-neutral-500">{stock.name}</p></div><div><p className="font-mono text-sm text-black">${stock.price.toFixed(2)}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-neutral-500">{stock.volume} vol</p></div><Change value={stock.change} /><Sparkline values={stock.sparkline} /><ChevronRight className="h-4 w-4 text-neutral-400" /></button>;
}

function Overview({ stocks, news, onSelect }: { stocks: StockItem[]; news: NewsItem[]; onSelect: (stock: StockItem) => void }) {
  const leaders = [...stocks].sort((a, b) => b.change - a.change).slice(0, 5);
  const gainers = stocks.filter((stock) => stock.change > 0).length;
  return <div className="space-y-16">
    <section className="grid gap-10 border-b border-black pb-12 lg:grid-cols-[1.5fr_1fr] lg:gap-20"><div><p className="mb-5 text-[10px] font-bold uppercase tracking-[0.3em] text-neutral-500">Tuesday / September 01, 2026</p><h1 className="max-w-3xl text-5xl font-semibold leading-[0.98] tracking-[-0.05em] text-black sm:text-7xl">A clearer view of the market.</h1><p className="mt-7 max-w-xl text-base leading-7 text-neutral-600">StreetLevel turns market noise into a short list of signals, context, and decisions worth making.</p><div className="mt-8 flex flex-wrap gap-3"><button className="inline-flex items-center gap-2 bg-black px-5 py-3 text-xs font-bold uppercase tracking-wider text-white hover:bg-neutral-800"><Search className="h-4 w-4" /> Explore signals</button><button className="inline-flex items-center gap-2 border border-black px-5 py-3 text-xs font-bold uppercase tracking-wider text-black hover:bg-black hover:text-white"><Download className="h-4 w-4" /> Export brief</button></div></div><div className="self-end border-l border-black pl-6 lg:pl-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-neutral-500">Market note / 09:42 ET</p><p className="mt-5 text-xl font-medium leading-8 text-black">Breadth is constructive, but leadership remains concentrated in semiconductors.</p><div className="mt-8 grid grid-cols-2 gap-6"><Metric label="Breadth" value={`${gainers}/${stocks.length}`} note="symbols advancing" /><Metric label="Volatility" value="18.45" note="VIX index" /></div></div></section>
    <section><SectionHeading eyebrow="At a glance" title="Today’s operating picture" action="Open performance" /><div className="grid gap-x-8 gap-y-10 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Portfolio value" value="$73,013" note="+$1,245.80 / +1.74% today" large /><Metric label="Active signals" value="24" note="4 high-conviction setups" large /><Metric label="Watchlist" value={`${stocks.length} names`} note="Feed latency under 150ms" large /><Metric label="Open alerts" value="12" note="2 require review" large /></div></section>
    <section className="grid gap-12 lg:grid-cols-[1.25fr_0.75fr]"><div><SectionHeading eyebrow="Momentum" title="Leaders in motion" action="View all names" /><div className="border-t border-black"><div className="hidden grid-cols-[1.1fr_1fr_0.8fr_1fr_28px] gap-4 border-b border-neutral-300 py-3 text-[10px] font-bold uppercase tracking-[0.18em] text-neutral-500 sm:grid"><span>Asset</span><span>Last / volume</span><span>Change</span><span>Trend</span><span /></div>{leaders.map((stock) => <StockRow key={`${stock.symbol}-${stock.price}`} stock={stock} onSelect={onSelect} />)}</div></div><div><SectionHeading eyebrow="The wire" title="What changed" action="Read all" /><div className="divide-y divide-neutral-200 border-y border-black">{news.slice(0, 5).map((item) => <article key={item.id} className="py-5"><div className="flex items-center justify-between gap-3 text-[10px] font-bold uppercase tracking-wider text-neutral-500"><span>{item.source}</span><span>{item.time}</span></div><h3 className="mt-2 text-sm font-semibold leading-5 text-black">{item.title}</h3><div className="mt-3 flex items-center justify-between"><span className="font-mono text-[10px] text-neutral-500">{item.relatedSymbol}</span><span className="text-[10px] uppercase tracking-wider text-neutral-500">{item.category}</span></div></article>)}</div></div></section>
    <SignalBoard stocks={stocks} onSelect={onSelect} />
  </div>;
}

function SignalBoard({ stocks, onSelect }: { stocks: StockItem[]; onSelect: (stock: StockItem) => void }) {
  const [filter, setFilter] = useState("All");
  const signals = useMemo(() => stocks.filter((stock) => filter === "All" || stock.signals.sentiment === filter), [filter, stocks]);
  return <section><SectionHeading eyebrow="Signal board" title="A working list, not a feed" action="Manage rules" /><div className="mb-5 flex items-center justify-between border-y border-black py-3"><div className="flex gap-4">{["All", "Bullish", "Neutral", "Bearish"].map((option) => <button key={option} onClick={() => setFilter(option)} className={`text-[10px] font-bold uppercase tracking-wider ${filter === option ? "text-black underline underline-offset-4" : "text-neutral-500 hover:text-black"}`}>{option}</button>)}</div><span className="font-mono text-[10px] text-neutral-500">{signals.length} results</span></div><div className="grid gap-x-8 sm:grid-cols-2 lg:grid-cols-3">{signals.slice(0, 9).map((stock) => <button key={`${stock.symbol}-signal`} onClick={() => onSelect(stock)} className="group border-b border-neutral-200 py-5 text-left hover:border-black"><div className="flex items-start justify-between"><div><p className="font-mono text-sm font-bold text-black">{stock.symbol}</p><p className="mt-2 text-sm leading-5 text-neutral-600">{stock.signals.sentiment} momentum with {stock.signals.bollinger.toLowerCase()} band position.</p></div><span className="font-mono text-lg text-black">{stock.signals.zScore.toFixed(1)}σ</span></div><div className="mt-5 flex items-center justify-between text-[10px] uppercase tracking-wider text-neutral-500"><span>RSI {stock.signals.rsi}</span><span className="group-hover:text-black">Inspect <ChevronRight className="ml-1 inline h-3 w-3" /></span></div></button>)}</div></section>;
}

function Watchlist({ stocks, onSelect }: { stocks: StockItem[]; onSelect: (stock: StockItem) => void }) {
  const [query, setQuery] = useState("");
  const filtered = stocks.filter((stock) => `${stock.symbol} ${stock.name} ${stock.sector}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-10"><SectionHeading eyebrow="Coverage / {stocks.length} assets" title="Watchlist" /><div className="flex flex-col gap-4 border-y border-black py-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-0 top-2 h-4 w-4 text-neutral-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by symbol, company, or sector" className="h-8 w-full border-0 bg-transparent pl-7 text-sm text-black outline-none placeholder:text-neutral-500" /></label><button className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-neutral-500 hover:text-black"><Filter className="h-4 w-4" /> Filter</button><button className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-neutral-500 hover:text-black"><SlidersHorizontal className="h-4 w-4" /> Columns</button></div><div className="grid gap-x-10 md:grid-cols-2">{filtered.map((stock) => <StockRow key={`${stock.symbol}-${stock.name}`} stock={stock} onSelect={onSelect} />)}</div></div>;
}

function Analytics({ stocks }: { stocks: StockItem[] }) {
  const sectors = ["All sectors", ...Array.from(new Set(stocks.map((stock) => stock.sector)))];
  const [selectedSector, setSelectedSector] = useState("All sectors");
  const [selected, setSelected] = useState(stocks[0].symbol);
  const sectorStocks = selectedSector === "All sectors" ? stocks : stocks.filter((stock) => stock.sector === selectedSector);
  const stock = sectorStocks.find((item) => item.symbol === selected) ?? sectorStocks[0] ?? stocks[0];
  const sectorChange = sectorStocks.reduce((sum, item) => sum + item.change, 0) / sectorStocks.length;
  const sectorRsi = sectorStocks.reduce((sum, item) => sum + item.signals.rsi, 0) / sectorStocks.length;
  const bullishCount = sectorStocks.filter((item) => item.signals.sentiment === "Bullish").length;
  const range = stock.high52 - stock.low52;
  const position = ((stock.price - stock.low52) / range) * 100;
  return <div className="space-y-12"><SectionHeading eyebrow="Technical review" title="Analytics" /><div className="grid gap-4 border-y border-black py-4 md:grid-cols-[1fr_1fr_auto] md:items-center"><label className="flex items-center gap-3"><span className="text-[10px] font-bold uppercase tracking-wider text-neutral-500">Sector</span><select value={selectedSector} onChange={(event) => { const nextSector = event.target.value; const nextStocks = nextSector === "All sectors" ? stocks : stocks.filter((item) => item.sector === nextSector); setSelectedSector(nextSector); setSelected(nextStocks[0]?.symbol ?? stocks[0].symbol); }} className="min-w-0 bg-transparent font-mono text-sm font-bold text-black outline-none">{sectors.map((sector) => <option key={sector}>{sector}</option>)}</select></label><label className="flex items-center gap-3"><span className="text-[10px] font-bold uppercase tracking-wider text-neutral-500">Stock</span><select value={stock.symbol} onChange={(event) => setSelected(event.target.value)} className="min-w-0 bg-transparent font-mono text-sm font-bold text-black outline-none">{sectorStocks.map((item) => <option key={item.symbol}>{item.symbol}</option>)}</select></label><span className="text-xs text-neutral-500">Updated 14:32:08 ET</span></div><div className="grid gap-8 border-b border-black pb-8 sm:grid-cols-3"><Metric label="Sector change" value={`${sectorChange >= 0 ? "+" : ""}${sectorChange.toFixed(2)}%`} note={`${sectorStocks.length} stocks in scope`} large /><Metric label="Average RSI" value={sectorRsi.toFixed(1)} note={`${bullishCount} bullish signals`} large /><Metric label="Selected stock" value={stock.symbol} note={stock.sector} large /></div><div className="grid gap-12 lg:grid-cols-[1.4fr_0.6fr]"><div><div className="flex items-end justify-between"><div><p className="font-mono text-5xl text-black">${stock.price.toFixed(2)}</p><div className="mt-3"><Change value={stock.change} /></div></div><Sparkline values={stock.sparkline} /></div><div className="mt-16 border-y border-black py-8"><div className="flex h-56 items-end gap-2">{stock.sparkline.concat(stock.sparkline).map((value, index) => <div key={`${value}-${index}`} className="flex-1 bg-black" style={{ height: `${30 + ((value - Math.min(...stock.sparkline)) / (Math.max(...stock.sparkline) - Math.min(...stock.sparkline) || 1)) * 70}%` }} />)}</div><div className="mt-4 flex justify-between text-[10px] uppercase tracking-wider text-neutral-500"><span>20 sessions ago</span><span>Today</span></div></div></div><div className="space-y-8"><Metric label="RSI / 14" value={String(stock.signals.rsi)} note="Momentum oscillator" large /><Metric label="SMA / 50" value={`$${stock.signals.sma50.toFixed(2)}`} note="Trend reference" /><Metric label="Bollinger" value={stock.signals.bollinger} note="Current band position" /><Metric label="52 week range" value={`${position.toFixed(0)}%`} note={`$${stock.low52.toFixed(0)} — $${stock.high52.toFixed(0)}`} /></div></div></div>;
}

function Signals({ stocks }: { stocks: StockItem[] }) { return <div className="space-y-10"><SectionHeading eyebrow="Rules / 12 active" title="Signals" action="New rule" /><div className="flex items-center justify-between border-y border-black py-4"><p className="text-sm text-neutral-600">Rules watch price, moving averages, and abnormal volume across your coverage.</p><button className="inline-flex items-center gap-2 bg-black px-4 py-2 text-xs font-bold uppercase tracking-wider text-white"><Plus className="h-4 w-4" /> Create rule</button></div><div className="divide-y divide-neutral-200 border-b border-black">{stocks.slice(0, 8).map((stock, index) => <div key={`${stock.symbol}-alert`} className="grid gap-4 py-5 sm:grid-cols-[1fr_1.5fr_0.7fr_24px] sm:items-center"><div><p className="font-mono text-sm font-bold text-black">{stock.symbol}</p><p className="mt-1 text-xs text-neutral-500">Rule SL-{String(index + 1).padStart(3, "0")}</p></div><p className="text-sm text-black">Notify when price {index % 2 === 0 ? "moves above" : "crosses 50 day average"}</p><span className="text-xs font-bold uppercase tracking-wider text-neutral-500">{index < 5 ? "Active" : "Paused"}</span><button aria-label={`More options for ${stock.symbol}`}><MoreHorizontal className="h-4 w-4 text-neutral-500" /></button></div>)}</div></div>; }

function Performance({ stocks }: { stocks: StockItem[] }) { const bullish = stocks.filter((stock) => stock.change > 0).length; const avgRsi = stocks.reduce((sum, stock) => sum + stock.signals.rsi, 0) / stocks.length; return <div className="space-y-14"><SectionHeading eyebrow="Attribution / current session" title="Performance" /><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Bullish names" value={`${bullish}`} note={`of ${stocks.length} covered`} large /><Metric label="Average RSI" value={avgRsi.toFixed(1)} note="14 day reading" large /><Metric label="Market theta" value="0.42h" note="Signal half-life" large /><Metric label="Risk budget" value="68%" note="Currently deployed" large /></div><section><SectionHeading eyebrow="Relative strength" title="Sector performance" />{["Semiconductors", "Software & Cloud", "Consumer Electronics", "Automotive & Clean Energy"].map((sector) => { const rows = stocks.filter((stock) => stock.sector === sector); const score = rows.length ? rows.reduce((sum, stock) => sum + stock.change, 0) / rows.length : 0; return <div key={sector} className="grid grid-cols-[1fr_100px_1fr] items-center gap-5 border-t border-neutral-200 py-5"><span className="text-sm font-semibold text-black">{sector}</span><span className="font-mono text-sm text-black">{score >= 0 ? "+" : ""}{score.toFixed(2)}%</span><div className="h-1 bg-neutral-200"><div className="h-full bg-black" style={{ width: `${Math.min(Math.abs(score) * 25, 100)}%` }} /></div></div>; })}</section><section><SectionHeading eyebrow="Risk lens" title="Portfolio risk assessment" /> <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{[["Beta", "1.28", "28% above market"], ["VaR / 95%", "-2.34%", "Expected one-day loss"], ["Sharpe ratio", "1.84", "Risk-adjusted return"], ["Max drawdown", "-8.42%", "Peak to trough"], ["Correlation", "0.72", "Versus S&P 500"], ["Sortino ratio", "2.47", "Downside adjusted"]].map(([label, value, note]) => <Metric key={label} label={label} value={value} note={note} large />)}</div></section></div>; }

function Insights({ stocks, news, onSelect }: { stocks: StockItem[]; news: NewsItem[]; onSelect: (stock: StockItem) => void }) { const top = [...stocks].sort((a, b) => b.change - a.change).slice(0, 5); const bottom = [...stocks].sort((a, b) => a.change - b.change).slice(0, 5); return <div className="space-y-14"><SectionHeading eyebrow="Context / signal quality" title="Insights" /><div className="grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Leaders" title="Top performers" />{top.map((stock, index) => <button key={`top-${stock.symbol}-${index}`} onClick={() => onSelect(stock)} className="flex w-full items-center justify-between border-t border-neutral-200 py-5 text-left hover:bg-neutral-100"><span className="flex items-center gap-4"><span className="font-mono text-xs text-neutral-500">0{index + 1}</span><span><strong className="block font-mono text-sm text-black">{stock.symbol}</strong><small className="text-xs text-neutral-500">{stock.name}</small></span></span><Change value={stock.change} /></button>)}</div><div><SectionHeading eyebrow="Drag" title="Underperformers" />{bottom.map((stock, index) => <button key={`bottom-${stock.symbol}-${index}`} onClick={() => onSelect(stock)} className="flex w-full items-center justify-between border-t border-neutral-200 py-5 text-left hover:bg-neutral-100"><span className="flex items-center gap-4"><span className="font-mono text-xs text-neutral-500">0{index + 1}</span><span><strong className="block font-mono text-sm text-black">{stock.symbol}</strong><small className="text-xs text-neutral-500">{stock.name}</small></span></span><Change value={stock.change} /></button>)}</div></div><section><SectionHeading eyebrow="Full archive" title="Market news" /> <div className="divide-y divide-neutral-200 border-y border-black">{news.map((item) => <article key={item.id} className="grid gap-3 py-5 md:grid-cols-[140px_1fr_100px] md:gap-8"><div className="text-[10px] font-bold uppercase tracking-wider text-neutral-500">{item.source}<br />{item.time}</div><h3 className="text-sm font-semibold leading-6 text-black">{item.title}</h3><div className="flex items-start justify-between gap-4 text-[10px] uppercase tracking-wider text-neutral-500"><span>{item.relatedSymbol}</span><ExternalLink className="h-3 w-3" /></div></article>)}</div></section></div>; }

function Portfolio() { const total = INITIAL_PORTFOLIO.reduce((sum, position) => sum + position.totalValue, 0); const pl = INITIAL_PORTFOLIO.reduce((sum, position) => sum + position.unrealizedPl, 0); return <div className="space-y-12"><SectionHeading eyebrow="Capital / live allocation" title="Portfolio" action="Export positions" /><div className="grid gap-8 border-y border-black py-8 sm:grid-cols-3"><Metric label="Total value" value={`$${total.toLocaleString(undefined, { maximumFractionDigits: 0 })}`} note="Across all positions" large /><Metric label="Unrealized P&L" value={`$${pl.toLocaleString(undefined, { maximumFractionDigits: 0 })}`} note="Since entry" large /><Metric label="Positions" value={String(INITIAL_PORTFOLIO.length)} note="Diversified exposure" large /></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b border-black text-[10px] font-bold uppercase tracking-wider text-neutral-500"><th className="py-4">Position</th><th>Shares</th><th>Avg cost</th><th>Last</th><th>Value</th><th className="text-right">P&L</th></tr></thead><tbody>{INITIAL_PORTFOLIO.map((position) => <tr key={position.id} className="border-b border-neutral-200 text-sm"><td className="py-5 font-mono font-bold text-black">{position.symbol}</td><td className="font-mono text-neutral-600">{position.shares}</td><td className="font-mono text-neutral-600">${position.avgCost.toFixed(2)}</td><td className="font-mono text-black">${position.currentPrice.toFixed(2)}</td><td className="font-mono text-black">${position.totalValue.toLocaleString()}</td><td className="text-right font-mono text-black">{position.unrealizedPlPercent >= 0 ? "+" : ""}{position.unrealizedPlPercent.toFixed(2)}%</td></tr>)}</tbody></table></div></div>; }

function SettingsView() { return <div className="space-y-12"><SectionHeading eyebrow="Workspace / preferences" title="Settings" /><div className="max-w-3xl divide-y divide-neutral-200 border-y border-black">{[["Display density", "Compact", "Choose how much data appears in each view"], ["Price alerts", "Enabled", "Receive notifications when a rule is triggered"], ["Volume spike alerts", "Enabled", "Watch for unusual volume across your list"], ["Sound effects", "Disabled", "Play an audio cue for important events"], ["Data retention", "30 days", "Keep historical quote data for backtesting"], ["API rate limit", "Standard", "Throttle ingest cadence during off-market hours"]].map(([label, value, description]) => <div key={label} className="flex items-center justify-between gap-6 py-6"><div><p className="text-sm font-semibold text-black">{label}</p><p className="mt-1 text-xs text-neutral-500">{description}</p></div><button className="border border-neutral-300 px-3 py-2 text-xs font-bold text-black hover:border-black">{value}</button></div>)}</div></div>; }

export default function StreetLevelDashboard() {
  const [activeTab, setActiveTab] = useState<TabType>("overview");
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [selectedStock, setSelectedStock] = useState<StockItem | null>(null);
  const content = activeTab === "overview" ? <Overview stocks={MOCK_STOCKS} news={MOCK_NEWS} onSelect={setSelectedStock} /> : activeTab === "watchlist" ? <Watchlist stocks={MOCK_STOCKS} onSelect={setSelectedStock} /> : activeTab === "analytics" ? <Analytics stocks={MOCK_STOCKS} /> : activeTab === "signals" ? <Signals stocks={MOCK_STOCKS} /> : activeTab === "performance" ? <Performance stocks={MOCK_STOCKS} /> : activeTab === "insights" ? <Insights stocks={MOCK_STOCKS} news={MOCK_NEWS} onSelect={setSelectedStock} /> : activeTab === "portfolio" ? <Portfolio /> : <SettingsView />;
  return <div className="min-h-screen bg-white text-black"><DashboardNav activeTab={activeTab} sidebarOpen={sidebarOpen} onTabChange={setActiveTab} onSidebarToggle={() => setSidebarOpen(!sidebarOpen)} /><DashboardTopBar activeTab={activeTab} onSidebarToggle={() => setSidebarOpen(!sidebarOpen)} /><main className="mx-auto max-w-[1500px] px-5 py-10 sm:px-10 lg:px-16"><div className="mb-10 flex items-center justify-between border-b border-neutral-300 pb-4"><div className="flex items-center gap-3"><span className="h-2 w-2 rounded-full bg-black" /><span className="text-[10px] font-bold uppercase tracking-[0.2em] text-neutral-500">Live research desk</span></div><div className="hidden items-center gap-5 text-[10px] font-bold uppercase tracking-wider text-neutral-500 md:flex"><span>NYSE / Open</span><span>14:32:08 ET</span><span>UTC -04:00</span></div></div>{content}<DashboardFooter /></main>{selectedStock && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-5" onClick={() => setSelectedStock(null)}><div className="w-full max-w-xl bg-white p-7 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between border-b border-black pb-6"><div><p className="font-mono text-sm font-bold">{selectedStock.symbol}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">{selectedStock.name}</h2></div><button onClick={() => setSelectedStock(null)} aria-label="Close detail"><X className="h-5 w-5" /></button></div><div className="grid gap-7 py-7 sm:grid-cols-2"><Metric label="Last price" value={`$${selectedStock.price.toFixed(2)}`} note={`${selectedStock.changeAmount >= 0 ? "+" : ""}$${selectedStock.changeAmount.toFixed(2)} today`} large /><Metric label="Signal" value={selectedStock.signals.sentiment} note={`Z-score ${selectedStock.signals.zScore.toFixed(1)}σ`} large /><Metric label="RSI / 14" value={String(selectedStock.signals.rsi)} note="Momentum oscillator" /><Metric label="P/E ratio" value={selectedStock.peRatio.toFixed(1)} note={selectedStock.sector} /></div><button className="flex w-full items-center justify-between border border-black px-4 py-3 text-xs font-bold uppercase tracking-wider hover:bg-black hover:text-white">Open full analysis <ChevronRight className="h-4 w-4" /></button></div></div>}</div>;
}
